version: '3.8'

services:
  postgres:
    build: # build指定を追加
      context: . # Dockerfileのディレクトリを指定
      dockerfile: db/Dockerfile # Dockerfileのパスを指定
    container_name: postgres-demo # コンテナ名を指定
    environment: # 環境変数を設定
      - POSTGRES_USER=${POSTGRES_USER} # データベースのユーザー名
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # ユーザーのパスワード
      - POSTGRES_DB=${POSTGRES_DB} # データベース名
    ports: # ポート番号を指定（ホスト:コンテナ）
      - 5432:5432
    volumes: # マッピングを指定
      - postgres_data:/var/lib/postgresql/data # データの永続化
      - ./db/initdb.d:/docker-entrypoint-initdb.d # 初期化用SQLのマウント

  main-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    container_name: main # コンテナ名を指定
    environment: # 環境変数を設定
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=${DATABASE_URL} # データベースのURL
      - POSTGRES_USER=${POSTGRES_USER} # データベースのユーザー名
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # ユーザーのパスワード
    tty: true # コンテナを終了させないために設定
    working_dir: /app # 作業ディレクトリを指定
    volumes: # マッピングを指定
      - ./main-service/build:/app/main-service/build
      - ./main-service/src:/app/main-service/src
      - ./shared/src:/app/shared/src
      - ./build.gradle:/app/build.gradle
      - ./gradlew:/app/gradlew
      - ./gradle:/app/gradle
      - ./settings.gradle:/app/settings.gradle
    ports: # ポート番号を指定（ホスト:コンテナ）
      - 8080:8080 # 実行用
      - 5005:5005 # デバッグ用
    depends_on: # postgresコンテナ起動後にspringコンテナを起動
      - postgres
      - localstack

  file-service:
    build:
      context: .
      dockerfile: file-service/Dockerfile
    container_name: file-service # コンテナ名を指定
    environment: # 環境変数を設定
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=${DATABASE_URL} # データベースのURL
      - POSTGRES_USER=${POSTGRES_USER} # データベースのユーザー名
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # ユーザーのパスワード
      - AWS_ACCESS_KEY_ID={AWS_ACCESS_KEY_ID} # アクセスキー
      - AWS_SECRET_ACCESS_KEY={AWS_SECRET_ACCESS_KEY} # シークレットアクセスキー
      - AWS_REGION=${AWS_REGION} # AWSのリージョン
    tty: true # コンテナを終了させないために設定
    working_dir: /app # 作業ディレクトリを指定
    volumes: # マッピングを指定
      - ./file-service/build:/app/file-service/build
      - ./file-service/src:/app/file-service/src
      - ./shared/src:/app/shared/src
      - ./build.gradle:/app/build.gradle
      - ./gradlew:/app/gradlew
      - ./gradle:/app/gradle
      - ./settings.gradle:/app/settings.gradle
    ports: # ポート番号を指定（ホスト:コンテナ）
      - 8081:8080 # 実行用
      - 5055:5005 # デバッグ用
    depends_on: # postgresコンテナ起動後にspringコンテナを起動
      - postgres
      - localstack

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3
      - DEFAULT_REGION=ap-northeast-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
volumes:
  postgres_data:
