spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  messages:
    encoding: UTF-8
  cloud:
    aws:
      region:
        static: {AWS_REGION}
      stack:
        auto: false
      credentials:
        access-key: {AWS_ACCESS_KEY_ID}
        secret-key: {AWS_SECRET_ACCESS_KEY}
        s3:
          endpoint: http://localstack:4566
          bucket: test-bucket
          url: http://localstack:4566/test-bucket
      sqs:
        endpoint: http://localstack:4566
        url: http://localstack:4566/000000000000/test-queue.fifo
        queue-name: test-queue.fifo

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org:
      jooq: DEBUG


spring:
  cloud:
    aws:
      region:
        static: {AWS_REGION}
      stack:
        auto: false
      credentials:
        access-key: {AWS_ACCESS_KEY_ID}
        secret-key: {AWS_SECRET_ACCESS_KEY}
        s3:
          endpoint: http://localstack:4566
          bucket: test-bucket
