spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  messages:
    encoding: UTF-8
  cloud:
    aws:
      region:
        static: ap-northeast-1
      stack:
        auto: false
      credentials:
        access-key: dummy
        secret-key: dummy
      sqs:
        endpoint: http://localstack:4566
        url: http://localstack:4566/000000000000/test-queue.fifo
        queue-name: test-queue.fifo

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org:
      jooq: DEBUG
