# Use the official PostgreSQL image
FROM postgres:latest

## Copy initialization scripts (if any)
#COPY docker/initdb.d /docker-initdb.d
#
## Set permissions for the scripts
## Note: This is done as root before switching to the postgres user
#USER root
#RUN chmod +x /docker-initdb.d/*.sh
#USER postgres
#
## Set the entrypoint (if custom)
#ENTRYPOINT ["/docker-initdb.d/entrypoint.sh"]
